### PR TITLE
Changes span class to macro

### PR DESCRIPTION
**Pull request by bigpep**
Туалет, ВХОД, Среда

### CODE REVIEW

**Comment by mattmatterson111** [comment]
I am in awe.

**Comment by bigpep** [comment]
I made it because I was curious if the repo allowed contribution or just
exists as a place for people to steal your code and add furries to it.

**Comment by mattmatterson111** [comment]
I mean you could probably see by the previous PRs that yes, contribution is allowed. And so far no one has made a furry codebase from this as far as I can tell. Unfortunately 919 files is **a lot** for me to look over, so I haven't gotten around to properly reviewing this PR yet.

**Comment by bigpep** [comment]
is that a suggestion?

**Comment by mattmatterson111** [comment]
A nice gesture, but I don't think I am ever going to get around to reviewing and merging this. I appreciate your effort though.

**Pull request closed without merging**
